### PR TITLE
Chore/bump runtime

### PR DESCRIPTION
**Pull request by jkoenig134**

### CODE REVIEW

**Comment by Milena-Czierlinski** [comment]
I think line 4 in `packages/enmeshed-runtime-bridge/lib/src/events/transport/relationship_decomposed_by_self_event.dart` needs to be adjusted, as well.

**Comment by jkoenig134** [comment]
@Milena-Czierlinski naaah, i dont want to create a class for that.

**Comment by jkoenig134** [comment]
This is not the place where everything went wrong.

**Comment by Milena-Czierlinski** [comment]
But wouldn't e.g. `Object` be more correct than `String`?

**Comment by jkoenig134** [comment]
Object is too imprecise

**Comment by jkoenig134** [comment]
everything is an Object in dart:

```dart
void main(List<String> args) {
 Object x = 1;

  print(x);
}
```

**Comment by britsta** [comment]
> I think line 4 in `packages/enmeshed-runtime-bridge/lib/src/events/transport/relationship_decomposed_by_self_event.dart` needs to be adjusted, as well.

I came to the same conclusion as Milena, when comparing this event with the `OwnSharedAttributeSucceededEvent`. In the corresponding file, we have the declarations `  final LocalAttributeDTO predecessor` and `final LocalAttributeDTO successor`. So maybe we need to adjust line 4 in `packages/enmeshed-runtime-bridge/lib/src/events/transport/relationship_decomposed_by_self_event.dart` to `final String relationshipId`.

**Comment by jkoenig134** [comment]
@britsta nice, that was the issue!

**Review by Milena-Czierlinski — APPROVED** [review]

**Pull request merged**
