### PR TITLE
Chore/Bump Runtime to 6.6.0

### PR DESCRIPTION
**Pull request by Milena-Czierlinski**
https://github.com/nmshd/runtime/compare/6.5.0...6.6.0

### CODE REVIEW

**Comment by jkoenig134** [comment]
I'm confused, where is the actual code for the forIdentity feature?

**Comment by Milena-Czierlinski** [comment]
> I'm confused, where is the actual code for the forIdentity feature?

In the runtime. ;) The facades only have an argument `query` that doesn't seem to be further specified.

**Comment by jkoenig134** [comment]
> The facades only have an argument query that doesn't seem to be further specified.

Ehrm, no! for createToken et al you need to have forIdentity as a paremeter

**Comment by jkoenig134** [comment]
Oh, 6.6.0 is only personalization filtering? The personalization itself came in earlier?

**Comment by Milena-Czierlinski** [comment]
> Oh, 6.6.0 is only personalization filtering? The personalization itself came in earlier?

Exactly :)

**Review by jkoenig134 — APPROVED** [review]
LAwesomeTM

**Pull request merged**
