### PR TITLE
chore/bump runtime

### PR DESCRIPTION
**Pull request by Magnus-Kuhn**

### CODE REVIEW

**Comment by jkoenig134** [comment]
@Magnus-Kuhn have you checked the diff between these versions?

**Review by Magnus-Kuhn — COMMENTED** [review]
> @Magnus-Kuhn have you checked the diff between these versions? 

I initially believed you but now I checked :)
`getSharedAttributesFromRequest` has made its way into the index.js, so it worked.

**Comment by jkoenig134** [comment]
this is not what I meant - if you bump the version here you have to make sure all diffs get added to the dart code. This means you have to check the runtime diff between `4.13.1` and `4.14.2`. 

@britsta can you make sure to double-check this?

**Review by britsta — APPROVED** [review]
Should be fine 🐸 FYI, version changes in main of the Runtime were made in the following PRs:
- Version change from `4.13.1` to `4.14.2`: https://github.com/nmshd/runtime/pull/155
- Version change from `4.13.2` to `4.14.0`: For the `DeleteSharedAttributesForRejectedOrRevokedRelationshipUseCase` added in PR https://github.com/nmshd/runtime/pull/173 we decided not to expose it to the App (see https://github.com/nmshd/app/pull/216#discussion_r1672293297).
- Version change from `4.14.0` to `4.14.1`: https://github.com/nmshd/runtime/pull/199
- Version change from `4.14.1` to `4.14.2`: https://github.com/nmshd/runtime/pull/206

In these and no other PRs that have been merged into main of the Runtime between version `4.13.1` to `4.14.2`, I have noticed changes relevant to the App-Runtime bridge.

**Review by jkoenig134 — APPROVED** [review]

**Pull request merged**
